export const countryCodes = [
  { label: "🇷🇺+7", code: "+7" },
  { label: "🇺🇸+1", code: "+1" },
  { label: "🇨🇦+1", code: "+1" },
  { label: "🇩🇪+49", code: "+49" },
  { label: "🇫🇷+33", code: "+33" },
  { label: "🇪🇸+34", code: "+34" },
  { label: "🇮🇹+39", code: "+39" },
  { label: "🇬🇧+44", code: "+44" },
  { label: "🇨🇳+86", code: "+86" },
  { label: "🇯🇵+81", code: "+81" },
  { label: "🇦🇺+61", code: "+61" },
  { label: "🇮🇳+91", code: "+91" },
  { label: "🇰🇷+82", code: "+82" },
  { label: "🇧🇷+55", code: "+55" },
  { label: "🇲🇽+52", code: "+52" },
  { label: "🇿🇦+27", code: "+27" },
];
